### PR TITLE
feature: expanded growth values  [SCHOOL-139] 

### PR DESCRIPTION
**Pull request by Camus1859**

### CODE REVIEW

**Comment by Camus1859** [comment]
The UI shows "-" for growth while Toms data has an actual number for growth. This happens in a few places and is giving errors.
@nbey @themightychris

**Comment by holly-g** [comment]
@themightychris @nbey for review

**Comment by themightychris** [comment]
@Camus1859 looks like one value is off, and the way `null` values are compared is off. Now that `slate-cbl` is fully updated and passing in this branch, you should be able to reproduce this locally by doing a clean checkout of the current version of this branch and running testing within the `b21-skeleton` repo.

When you use the "open in IDE" button and then make edits to the failing tests, they'll show as new files being added to the `b21-skeleton` repo (since the test script sources live in `slate-cbl`). Go ahead and commit your changes to this PR for now so we can see it passing, and then after we see this PR passing we'll copy the changes to those files down to the `slate-cbl` repo and then remove them from this PR and update the `slate-cbl` version instead before merging it

Screen Shot 2022-01-18 at 10 33 48 AM

Screen Shot 2022-01-18 at 10 33 21 AM

**Comment by themightychris** [comment]
To get this PR merged, please create an isolated commit that changes expected values as needed to get the test passing, documenting that these values disagree with the test cases document. We will then plan follow-up tickets that address these discrepancies and change the expected value back alongside the work to correct the value that comes out

So:

- Focus on getting this PR passing
- Capture in a commit we can use as a TODO list all the places we have to change the expected values to match the current UI rather than the test doc

**Comment by themightychris** [comment]
We discussed some strategy tweaks to how we address this PR. There are two potential sources of failures

1. Errors in Slate's calculation of values (shared code)
2. Errors in Slate's rendering of values (separate code for CSV, API, and UI)
  - This includes making sure `null` values render as blank or dash, and `0` values render as `0`

Errors of type #2 we should try to fix within this PR.

For errors of type #1, we need to address changing calculations in their own PRs. So to get this PR passing, make changes to our test case data to reflect the current incorrect calculations, and isolate such changes in 1 or more dedicated commits. We will then use those commits as reference as described in my last comment

**Comment by Camus1859** [comment]
Only growth was changed.

Student3:
   SCI.3: "-2.7" ----> null
   
Student4:
   ELA.1:"0" ---> null
   ELA.3:"1" ---> null
   ELA.4:"0.7" ---> null
   ELA.5:"1" ---> null
   ELA.7:"0.4" ---> null
   SCI.1:"-0.3" ---> null
   HOS.1:"0.8" ---> null
   HW.1:"0" ---> null
   HW.3:"1.2" ---> null

**Comment by themightychris** [comment]
I just merged the overrides in this PR upstream, it won't pass until https://github.com/SlateFoundation/slate-cbl/pull/654 gets merged and then this branch gets rebased on top of a `b21-skeleton#develop` that has the latest `slate-cbl` version

**Pull request merged**
