### PR TITLE
fix: student growth calculation [SCHOOL-101]

### PR DESCRIPTION
**Pull request by nbey**
This is going to fail until: https://github.com/SlateFoundation/slate-cbl/pull/663 gets reviewed/merged.

### CODE REVIEW

**Comment by themightychris** [comment]
@nbey I just released the slate-cbl update with your other PR merged and rebased this one

I expect we should see the tests fail one further down now than this `-2.7` value until we revert a lot more expected value changes: https://github.com/b21network/b21-skeleton/compare/b6251ac9e4ea82407a8f5125d0a09134929a06ab...6301162bb3621e7ca393441b02ad25e85c8630c2

**Comment by nbey** [comment]
@themightychris The rest of the changes are accounted for -- they all have `null` baseline and should have no growth.

**Comment by themightychris** [comment]
@nbey the original values all came from Tom's Google doc of test cases so we might still have an issue if what's coming out doesn't match that doc, you should be able to find a link to it within the Jira tickets, see if you can line up the other expected values that got changed to rows in the doc

**Comment by themightychris** [comment]
@nbey we're passing all tests now with the slate-cbl upgrade! Is there any reason this should stay in draft still or can we get it merged now?

**Pull request merged**
